project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "qmd/*.qmd"

website:
  title: "Project_R"
  site-url: "https://zaineb-ben-fadhl.github.io/Project_R/"
  repo-url: "https://github.com/zaineb-ben-fadhl/Project_R"
  
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Projects
        contents:
          - qmd/Project_R.qmd
          
          
         
      - section: Presentations
        contents:
          - qmd/presentation.qmd
     

format:
  html:
    theme: light
    css: thpe.css
    toc: true
    number-sections: true
    code-fold: true
    code-summary: "Show code"
    code-link: true
    code-overflow: scroll
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
    papersize: a4
    geometry:
      - top=20mm
      - left=25mm
      - bottom=25mm

# Configuration WebR (R seulement)
webr:
  packages: ["dplyr", "ggplot2", "readxl", "tidyr", "lubridate", "car", "lmtest"]

execute:
  freeze: true
  cache: false
  echo: false
  warning: false
  message: false
  engine: r  # ← FORCER l'utilisation de R seulement

# DÉSACTIVER Jupyter
kernel:
  jupyter: false

bibliography: bib.bib
csl: apa.csl

latex-auto-install: true